config/routes.rb
Itemcartholdon::Application.routes.draw do

  get 'cleandb' => "misc#cleandb", :as => :clean_db

  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  root :to => 'home#index'

  resources :itemholdons

end

app/models/itemholdon.rb
class Itemholdon < ActiveRecord::Base
end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout 'embedded_app'

  def index
    #@products = ShopifyAPI::Shop.find(:all, :params => {:limit => 10})
    @products = ShopifyAPI::Product.find :all
  end

end

app/controllers/itemholdons_controller.rb
class ItemholdonsController < ApplicationController
  before_action :set_itemholdon, only: [:show, :edit, :update, :destroy]

  # GET /itemholdons
  # GET /itemholdons.json
  def index
    @itemholdons = Itemholdon.all
  end

  # GET /itemholdons/1
  # GET /itemholdons/1.json
  def show
  end

  # GET /itemholdons/new
  def new
    if params[:shopifyId] != ''
        @itemholdon = Itemholdon.find_by shopifyId: params[:shopifyId]
        unless @itemholdon
            @itemholdon = Itemholdon.new(create_from_shopify_params)
        else
            @product = ShopifyAPI::Product params[:shopifyId]
        end
    else
        @itemholdon = Itemholdon.new(create_from_shopify_params)
    end
  end

  # GET /itemholdons/1/edit
  def edit
  end

  # POST /itemholdons
  # POST /itemholdons.json
  def create
    @itemholdon = Itemholdon.new(itemholdon_params)

    respond_to do |format|
      if @itemholdon.save
        format.html { redirect_to @itemholdon, notice: 'Itemholdon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @itemholdon }
      else
        format.html { render action: 'new' }
        format.json { render json: @itemholdon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itemholdons/1
  # PATCH/PUT /itemholdons/1.json
  def update
    respond_to do |format|
      if @itemholdon.update(itemholdon_params)
        format.html { redirect_to @itemholdon, notice: 'Itemholdon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @itemholdon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemholdons/1
  # DELETE /itemholdons/1.json
  def destroy
    @itemholdon.destroy
    respond_to do |format|
      format.html { redirect_to itemholdons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itemholdon
      @itemholdon = Itemholdon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itemholdon_params
      params.require(:itemholdon).permit(:shopifyId, :minStock, :active, :untilDate)
    end

    def create_from_shopify_params
        params.permit(:shopifyId)
    end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController

  def cleandb
    ActiveRecord::Base.connection.execute("delete from shops")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itemholdons_helper.rb
module ItemholdonsHelper
end

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home",
      icon: "<%= asset_path('faveicon.png') %>"
    });
  });

</script>
<h3>Products</h3>
<table>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %> - <%= product.title %> - <a href="itemholdons/new?shopifyId=<%= product.id %>">Set HoldOn Product</a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/itemholdons/_form.html.erb
<%= form_for(@itemholdon) do |f| %>
  <% if @itemholdon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itemholdon.errors.count, "error") %> prohibited this itemholdon from being saved:</h2>

      <ul>
      <% @itemholdon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shopifyId %><br>
    <%= f.text_field :shopifyId %>
  </div>
  <div class="field">
    <%= f.label :minStock %><br>
    <%= f.number_field :minStock %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :untilDate %><br>
    <%= f.datetime_select :untilDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itemholdons/edit.html.erb
<h1>Editing itemholdon</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemholdon %> |
<%= link_to 'Back', itemholdons_path %>

app/views/itemholdons/index.html.erb
<h1>Listing itemholdons</h1>

<table>
  <thead>
    <tr>
      <th>Shopifyid</th>
      <th>Minstock</th>
      <th>Active</th>
      <th>Untildate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @itemholdons.each do |itemholdon| %>
      <tr>
        <td><%= itemholdon.shopifyId %></td>
        <td><%= itemholdon.minStock %></td>
        <td><%= itemholdon.active %></td>
        <td><%= itemholdon.untilDate %></td>
        <td><%= link_to 'Show', itemholdon %></td>
        <td><%= link_to 'Edit', edit_itemholdon_path(itemholdon) %></td>
        <td><%= link_to 'Destroy', itemholdon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itemholdon', new_itemholdon_path %>

app/views/itemholdons/new.html.erb
<h1><% if defined?product %><%= @product.title %><% end %>Add HoldOn</h1>

<%= render 'form' %>

<%= link_to 'Back', itemholdons_path %>

app/views/itemholdons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shopifyid:</strong>
  <%= @itemholdon.shopifyId %>
</p>

<p>
  <strong>Minstock:</strong>
  <%= @itemholdon.minStock %>
</p>

<p>
  <strong>Active:</strong>
  <%= @itemholdon.active %>
</p>

<p>
  <strong>Untildate:</strong>
  <%= @itemholdon.untilDate %>
</p>

<%= link_to 'Edit', edit_itemholdon_path(@itemholdon) %> |
<%= link_to 'Back', itemholdons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itemcartholdon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: '<%= "https://#{ @shop_session.url }" if @shop_session %>'
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/misc/cleandb.html.erb
shops cleaned